/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package grama.ihm.view;

import grama.calcule.matrix.FloydWarshall;
import grama.graph.Noeud;
import static grama.graph.Noeud.getMostOpenNode;
import grama.ihm.DrawGraphPanel;
import grama.ihm.MainInterface;

/**
 *
 * @author twarr
 */
public class Comparaison extends InfoAbstractPanel {

    /**
     * Creates new form Comparaison
     */
    public Comparaison(MainInterface parent) {
        super(parent);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ouverteLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        gastronomiqueLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        culturelleLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(4, 0));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setText("Comparaison entre deux noeuds :");
        add(titleLabel);

        jPanel1.setLayout(new java.awt.BorderLayout());

        ouverteLabel.setText("Choisisser deux noeuds");
        jPanel1.add(ouverteLabel, java.awt.BorderLayout.CENTER);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(gastronomiqueLabel, java.awt.BorderLayout.CENTER);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(culturelleLabel, java.awt.BorderLayout.CENTER);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void update() {
        DrawGraphPanel graphPanel = getParent().getDrawGraphPanel();
        Noeud selected0 = graphPanel.getSelectedNodes()[0];
        Noeud selected1 = graphPanel.getSelectedNodes()[1];
        if (selected0 != null && selected1 != null){
            if (getMostOpenNode(selected0,selected1,graphPanel.getGraph(),FloydWarshall.getInstanceSaut(),Noeud.Type.ALL)){
                ouverteLabel.setText(selected0.getNom() +" est plus ouverte que "+selected1.getNom());
            }
            else{
                ouverteLabel.setText(selected0.getNom() +" est moins ouverte que "+selected1.getNom());
            }
            
            if (getMostOpenNode(selected0,selected1,graphPanel.getGraph(),FloydWarshall.getInstanceSaut(),Noeud.Type.RESTAURANT)){
                gastronomiqueLabel.setText(selected0.getNom() +" est plus gastronimique que "+selected1.getNom());
            }
            else{
                gastronomiqueLabel.setText(selected0.getNom() +" est moins gastronomique que "+selected1.getNom());
            }
            
            if (getMostOpenNode(selected0,selected1,graphPanel.getGraph(),FloydWarshall.getInstanceSaut(),Noeud.Type.LOISIR)){
                culturelleLabel.setText(selected0.getNom() +" est plus culturelle que "+selected1.getNom());
            }
            else{
                culturelleLabel.setText(selected0.getNom() +" est moins culturelle que "+selected1.getNom());
            }
        }
        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel culturelleLabel;
    private javax.swing.JLabel gastronomiqueLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel ouverteLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
