/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package grama.ihm;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.Insets;

/**
 * Permet d'ajouté une légende pour le graph
 *
 * @author twarr
 */
public class Legende extends javax.swing.JPanel {

    private LegendLigneComponent ligne;
    private LegendRondComponent rondCorrespondant;

    public Legende() {
        initComponents();
        LegendRondComponent rondSelect = new LegendRondComponent(Color.yellow);
        this.rondCorrespondant = new LegendRondComponent(Color.CYAN);
        this.ligne = new LegendLigneComponent(Color.yellow);

        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        c.ipadx = 20;
        c.ipady = 20;
        c.insets = new Insets(0, 0, 0, 4);
        add(rondSelect, c);

        c.gridx = 2;
        c.gridy = 0;
        c.insets = new Insets(0, 0, 0, 4);
        add(rondCorrespondant, c);

        c.gridx = 4;
        c.gridy = 0;
        c.insets = new Insets(15, 0, 0, 4);
        add(ligne, c);
    }

    public void setTextNoeudCorrespondant(String txt) {
        nodeCorrespond.setText(txt);
    }

    /**
     * masque ou affiche la légende pour les chemin
     *
     * @param bool true pour afficher et false pour masquer
     */
    public void cheminVisible(boolean bool) {
        ligne.setVisible(bool);
        linkPath.setVisible(bool);
    }

    /**
     * masque ou affiche la légende pour les noeud correspondant
     *
     * @param bool true pour afficher et false pour masquer
     */
    public void NoeudCorrespondVisible(boolean bool) {
        rondCorrespondant.setVisible(bool);
        nodeCorrespond.setVisible(bool);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nodeSelected = new javax.swing.JLabel();
        nodeCorrespond = new javax.swing.JLabel();
        linkPath = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(50, 30));
        setMinimumSize(new java.awt.Dimension(50, 30));
        setPreferredSize(new java.awt.Dimension(50, 30));
        setLayout(new java.awt.GridBagLayout());

        nodeSelected.setText("Noeud séléctionné");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 40);
        add(nodeSelected, gridBagConstraints);

        nodeCorrespond.setText("Noeud correspondant");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 40);
        add(nodeCorrespond, gridBagConstraints);

        linkPath.setText("Chemin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 40);
        add(linkPath, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel linkPath;
    private javax.swing.JLabel nodeCorrespond;
    private javax.swing.JLabel nodeSelected;
    // End of variables declaration//GEN-END:variables
}
